First attempt at creating bylaws for our group
aalmiray/java-champions pull request #217
Opened 2024-05-29 01:52 UTC by windust

2024-05-29 01:59 UTC, henri-tremblay commented on site/documents/bylaws/bylaws.md
> +Membership is open to individuals who have been nominated by a current Java Champion Member and approved by the Java Champion Group.
If should be "the group" here instead of "Java Champion Group"

2024-05-29 04:53 UTC, aalmiray commented on site/documents/bylaws/bylaws.md
> +Membership is open to individuals who have been nominated by a current Java Champion Member and approved by the Java Champion Group.
Indeed. There are a couple of instances where "the Group" should be used instead of "Java Champion group".

2024-05-29 04:56 UTC, aalmiray requested changes

2024-05-29 04:56 UTC, aalmiray commented on site/documents/bylaws/bylaws.md
> +A current Java Champion nominates an individual by submitting the form on [Typeform](https://form.typeform.com/to/dMS1s8). The nomination requires both a nominator and a co-nominator.
The use of "current" implies there may be more than one status. This needs clarification.

2024-05-31 18:52 UTC, kabutz commented
I think renouncing membership is a bit more involved than just a PR to this group, or at least should be. The best, IMHO would be to change the status to "renounced" or something like that, rather than just remove them, otherwise someone else might notice they are gone and add them back. They should also inform at least the Oracle Java Champion Team that they no longer are a JC. IMHO it would be best to also let the other JCs know via our mailing list.

2024-05-31 19:51 UTC, rokon12 commented
> I think renouncing membership is a bit more involved than just a PR to this group, or at least should be. The best, IMHO would be to change the status to "renounced" or something like that, rather than just remove them, otherwise someone else might notice they are gone and add them back. They should also inform at least the Oracle Java Champion Team that they no longer are a JC. IMHO it would be best to also let the other JCs know via our mailing list.

I'm curious about the circumstances under which someone would no longer want to be a Java Champion, unless they are joining Oracle.

2024-05-31 21:37 UTC, aalmiray commented
Java Champions that join Oracle as employees become Java Champions Alumni but they do not renounce the program. 

There have been only a handful of cases when a JC decided to leave the program. Reasons vary, you may find some of the details in the mailing list. Because of the nature of such details and the medium they were shared (private mailing list) I won't discuss any of them in this channel.

2024-06-01 14:53 UTC, aalmiray commented
We do have an icon indicating a JC has retired from the program. Look for the 🏖️

2024-06-01 16:50 UTC, windust commented on site/documents/bylaws/bylaws.md
> +Membership is open to individuals who have been nominated by a current Java Champion Member and approved by the Java Champion Group.
good point! Will fix

2024-06-01 16:51 UTC, windust commented on site/documents/bylaws/bylaws.md
> +A current Java Champion nominates an individual by submitting the form on [Typeform](https://form.typeform.com/to/dMS1s8). The nomination requires both a nominator and a co-nominator.
yeah, actually, thinking about it it's not necessary to say "current"

2024-06-01 17:16 UTC, windust commented
I wonder what does it mean to be retired? and how one retires? is that the same as renouncing? and what process do we do to get someone to retire? (we can probably start without that status maybe? Just thinking out loud.

2024-06-01 17:18 UTC, windust commented on site/documents/bylaws/bylaws.md
> +A current Java Champion nominates an individual by submitting the form on [Typeform](https://form.typeform.com/to/dMS1s8). The nomination requires both a nominator and a co-nominator.
I guess now we have three statuses

2024-06-01 18:14 UTC, aalmiray commented
The paragraph for renouncing membership uses the verb update twice in the same sentence 😅

2024-06-01 19:51 UTC, kabutz commented
These by-laws are excellent and very useful to display on our javachampions.org website. There is only one thing I would hide from public view, and that is the nomination form. We get DM requests on the Java_Champions twitter handle regularly from folks who would like to become Java Champions, and IMHO we shouldn't burden the team at Oracle with wading through scores of submissions from people who are not Java Champions. What do you think?

2024-06-01 19:56 UTC, windust commented
good point Heinz! One thing I have been mulling about is to have a private github repo that only champions have access to. This repo could then have the actual links for the voting form (and other resources that are java champion related). We could amend the bylaws to just specify the current adopted form, and leave it as that

2024-06-02 09:01 UTC, hendrikebbers commented on site/documents/bylaws/bylaws.md
> +The Group use of the Java Champions Logo is subject to Oracle's Term and Conditions. In particular the Group cannot create any merchandise that bears the Java Champions Logo
I do not know is that is correct:
- The current JC illustrations show the Java Duke in a specific pose. Duke is open source under the BSD licence (see https://www.oracle.com/uk/java/duke/) and Oracle encourage designers to create new duke motives. Can a Duke in a specific pose be subject to a company?
- The current illustration (https://github.com/aalmiray/java-champions/blob/main/site/assets/img/duke_champion.png) was ordered by me several years ago from a designer to create JC stickers. I gave it to @aalmiray to publish it OSS in this repo. Nobody complained about that. Oracle only provides a low-resolution Duke image
(https://pbs.twimg.com/profile_images/3220519779/9928f94d6fb7bc0024781fa68e0bc571_400x400.jpeg). Maybe Oracle owns that image, but I have no idea if they can own "Duke with laurel crown" in general.

We should ask ourselves If I did something "wrong" by ordering that Duke illustration and creating stickers out of it or we we want to use that Logo that does not belong to any company (if that is the case from a legal point of view).

2024-06-02 09:14 UTC, hendrikebbers approved these changes

2024-06-02 09:14 UTC, hendrikebbers commented on site/documents/bylaws/bylaws.md
> +A member may renounce their membership at any time by submitting a pull request to update their status in the [Java Champions List](https://github.com/aalmiray/java-champions/blob/main/java-champions
@aalmiray, what do you think about creating a JC org at GitHub?

2024-06-02 09:14 UTC, hendrikebbers commented on site/documents/bylaws/bylaws.md
> +Once a nomination has been submitted and processed by Oracle's Java Champion Team, it will be announced on the Group Mailing List. This initiates a two-week discussion period during which Group membe
Should we add the mail address of the mailing list + the groups.io link here?

2024-06-02 09:14 UTC, hendrikebbers commented on site/documents/bylaws/bylaws.md
> +Once a nomination has been submitted and processed by Oracle's Java Champion Team, it will be announced on the Group Mailing List. This initiates a two-week discussion period during which Group membe
I want to add a section that mentions that the organization and processing of the nomination today are done by Oracle / Oracle's Java Champion Team. The current text can be read that it is a must that Oracle is involved here. Do not get me wrong: I like that Oracle does it and do not want to change it, but we should make clear that it is not a must when we define bylaws.

2024-06-02 09:14 UTC, hendrikebbers commented on site/documents/bylaws/bylaws.md
> +Amendments must be approved by a two-thirds majority of the members voting in the poll.
Question: How can the bylaws be changed / edited in future? I assume we should define a process for that, too.

2024-06-02 09:16 UTC, hendrikebbers requested changes
Added some comments that I would like to discuss

2024-06-02 09:17 UTC, hendrikebbers commented
next to all my comments: Thanks @windust for creating this. I totally agree with @kabutz : Having that on our page would be a big benefit

2024-06-02 09:19 UTC, aalmiray commented on site/documents/bylaws/bylaws.md
> +Once a nomination has been submitted and processed by Oracle's Java Champion Team, it will be announced on the Group Mailing List. This initiates a two-week discussion period during which Group membe
No, because that information is private to the Group. There's at least one instance when an outsider tried to hack his way into the Group.

2024-06-02 09:41 UTC, ixchelruiz commented on site/documents/bylaws/bylaws.md
> +A member may renounce their membership at any time by submitting a pull request to update their status in the [Java Champions List](https://github.com/aalmiray/java-champions/blob/main/java-champions
In my personal experience, I have found that having one person accountable for a project like this is crucial to its prosperity (all JCs are still responsible and welcome to contribute). After more than 7 years since this repository was launched, I think this way of working is a proof of continuity. Andres has been relentless in keeping the visibility and exposure of how diverse the Java Champions community is.

2024-06-02 09:41 UTC, ixchelruiz commented on site/documents/bylaws/bylaws.md
> +Once a nomination has been submitted and processed by Oracle's Java Champion Team, it will be announced on the Group Mailing List. This initiates a two-week discussion period during which Group membe
The list is private

2024-06-02 09:43 UTC, aalmiray commented on site/documents/bylaws/bylaws.md
> +The Group use of the Java Champions Logo is subject to Oracle's Term and Conditions. In particular the Group cannot create any merchandise that bears the Java Champions Logo
Duke is open source but some illustrations of Duke aren't. Take for example these which are owned by Oracle ![image](https://github.com/aalmiray/java-champions/assets/13969/0f866c29-c359-407f-85fa-027dfbaa04d4)

2024-06-02 10:14 UTC, hendrikebbers commented on site/documents/bylaws/bylaws.md
> +The Group use of the Java Champions Logo is subject to Oracle's Term and Conditions. In particular the Group cannot create any merchandise that bears the Java Champions Logo
Sure. But that is exactly 1 illustration (like pixel by pixel). If we use the given Duke of this repo and create stickers or whatever I assume that won’t be a problem and we could do it. Based on that the written paragraph might be wrong (again, I’m not a lawyer, just do assumption)

2024-06-02 10:17 UTC, hendrikebbers commented on site/documents/bylaws/bylaws.md
> +A member may renounce their membership at any time by submitting a pull request to update their status in the [Java Champions List](https://github.com/aalmiray/java-champions/blob/main/java-champions
People already discuss about a private repo (to store info like the submission form or the mailing list details). Where to put that if we do not have an org? Actually I’m totally fine to have for 100% the same people and rights as we have today but an org would make it more official. As said, just a suggestion :)

2024-06-02 10:33 UTC, hendrikebbers commented on site/documents/bylaws/bylaws.md
> +A member may renounce their membership at any time by submitting a pull request to update their status in the [Java Champions List](https://github.com/aalmiray/java-champions/blob/main/java-champions
For me it would be 💯 % fine if Andrew creates that org, has full admin rights and maybe give that to a handful of additional JCs. He is doing a great job and I hope he continues that but I would favor to have a neutral / official org name.  I totally agree that you need an accountable person for such job and that he does it a great way.

2024-06-02 17:26 UTC, windust commented on site/documents/bylaws/bylaws.md
> +Amendments must be approved by a two-thirds majority of the members voting in the poll.
ah! That's article IV right? (or is that missing clarity?)

2024-06-02 17:45 UTC, windust commented on site/documents/bylaws/bylaws.md
> +Once a nomination has been submitted and processed by Oracle's Java Champion Team, it will be announced on the Group Mailing List. This initiates a two-week discussion period during which Group membe
Hm...I think because that's the way it's always been I have put it in the bylaws... BUT the good thing is that the bylaws says how to amend them as well. If we want to decide to change it we should just create an amendment. I think the main reason is that without explicitly calling out the role that Oracle plays we would immediately have to own the process (and while I am not against that), it takes some time to put everything together. I would rather first start with what we do with an option to amend later

2024-06-02 18:07 UTC, windust commented on site/documents/bylaws/bylaws.md
> +The Group use of the Java Champions Logo is subject to Oracle's Term and Conditions. In particular the Group cannot create any merchandise that bears the Java Champions Logo
Ah, this are guidelines that came directly from Oracle (it's on the list, last week I think). So they go in as is since that's what it is... but if later we talk and discover they are not as strict we can amend these :)

2024-06-02 18:08 UTC, windust commented on site/documents/bylaws/bylaws.md
> +Once a nomination has been submitted and processed by Oracle's Java Champion Team, it will be announced on the Group Mailing List. This initiates a two-week discussion period during which Group membe
(let me think about it... I guess essentially you are asking to split the ownership of the process into its own section? hm..

2024-06-02 21:18 UTC, evanchooly commented on site/documents/bylaws/bylaws.md
> +A member may renounce their membership at any time by submitting a pull request to update their status in the [Java Champions List](https://github.com/aalmiray/java-champions/blob/main/java-champions
fwiw, i name squarted on https://github.com/java-champions a few years back so "we" own that should we want to use it.  though there might be trademark issues with oracle over the name...

2024-06-02 21:54 UTC, ixchelruiz commented on site/documents/bylaws/bylaws.md
> +A member may renounce their membership at any time by submitting a pull request to update their status in the [Java Champions List](https://github.com/aalmiray/java-champions/blob/main/java-champions
The Java champions are a group of “people” …. first and foremost… with many members in the community contributing to highlight it…

2024-06-02 22:00 UTC, ixchelruiz commented on site/documents/bylaws/bylaws.md
> +A member may renounce their membership at any time by submitting a pull request to update their status in the [Java Champions List](https://github.com/aalmiray/java-champions/blob/main/java-champions
While I see some advantages to try to consolidate the efforts under a single system… I’m happy that individuals have taken the initiative to register the domain,  create a GitHub organization start a conference .. and write down the bylaws! … this has been done with the effort of very active individuals … I would not be surprised that adding extra layers of overhead would be in detrimental of said individual efforts ..

2024-06-03 06:39 UTC, kcpeppe commented on site/documents/bylaws/bylaws.md
> +The Group use of the Java Champions Logo is subject to Oracle's Term and Conditions. In particular the Group cannot create any merchandise that bears the Java Champions Logo
AFAIK, Duke is CC-no commercial. We can check with James Gosling to confirm.

2024-06-03 08:32 UTC, kabutz commented on site/documents/bylaws/bylaws.md
> +The Group use of the Java Champions Logo is subject to Oracle's Term and Conditions. In particular the Group cannot create any merchandise that bears the Java Champions Logo
No, Duke is BSD: https://www.oracle.com/java/duke.html

2024-06-03 09:10 UTC, karianna commented on site/documents/bylaws/bylaws.md
> +Members of the Group can fall into three categories.
```suggestion
Members of the Group can fall into three categories:

```

2024-06-03 09:10 UTC, karianna commented on site/documents/bylaws/bylaws.md
> + - Renounced: Members that have chosen to leave the Group
```suggestion
 1. Renounced: Members that have chosen to leave the Group

```

2024-06-03 09:10 UTC, karianna commented on site/documents/bylaws/bylaws.md
> + - Alumni: Members that have joined Oracle after becoming Java Champions
```suggestion
 1. Alumni: Members that have joined Oracle after becoming Java Champions

```

2024-06-03 09:10 UTC, karianna commented on site/documents/bylaws/bylaws.md
> + - Active: Members that are neither Renounced nor Alumni
```suggestion
 1. Active: Members that are neither Renounced nor Alumni

```

2024-06-03 09:10 UTC, karianna commented on site/documents/bylaws/bylaws.md
> +A Group member nominates an individual by submitting the nomination form. The nomination form is created and maintained by the Group. The nomination requires both a nominator and a co-nominator.
Can we link the form here?

2024-06-03 09:10 UTC, karianna commented on site/documents/bylaws/bylaws.md
> +After the two-week voting period, the results are tallied.
```suggestion
After the two-week voting period, the results are tallied:


```

2024-06-03 09:10 UTC, karianna commented on site/documents/bylaws/bylaws.md
> +Members have the right to attend meetings, vote on the Group matters, and participate in the Group activities. They are responsible for upholding the Group's mission and adhering to these bylaws.
We should link to the official mission if we have that stated.

2024-06-03 09:24 UTC, aalmiray commented on site/documents/bylaws/bylaws.md
> +A Group member nominates an individual by submitting the nomination form. The nomination form is created and maintained by the Group. The nomination requires both a nominator and a co-nominator.
No. That link must remain private. Someone has already exploited this link in the past.

2024-06-03 12:27 UTC, mthmulders commented on site/documents/bylaws/bylaws.md
> +The purpose of the Group is to recognize key influencers in the Java community, provide advice, advance the adoption, and support the Java language and platform.
```suggestion
The purpose of the Group is to recognize key influencers in the Java community, provide advice, advance the adoption of Java, and support the Java language and platform.

```

2024-06-03 12:27 UTC, mthmulders commented on site/documents/bylaws/bylaws.md
> +### Section 3: Nomination
Can we renumber sections 4 till 7 as 3a till 3d - they all belong logically together, don't they?

2024-06-03 12:27 UTC, mthmulders commented on site/documents/bylaws/bylaws.md
> +A member may renounce their membership at any time by submitting a pull request to update their status in the [Java Champions List](https://github.com/aalmiray/java-champions/blob/main/java-champions
I think that the current process for renouncement is _not_ creating a PR, but announcing it on the mailing list.

2024-06-03 12:27 UTC, mthmulders commented on site/documents/bylaws/bylaws.md
> +Voting on amendments to these bylaws shall be conducted by secret poll to ensure both transparency and privacy. Each member's vote shall be recorded without disclosing individual voting preferences.
This is significantly different from the voting for potential members. I feel that voting for potential candidates is more delicate than changing the bylaws. See also the subthread on the mailing list; maybe we should have it the other way around? ;-)

2024-06-03 12:30 UTC, aalmiray commented on site/documents/bylaws/bylaws.md
> +The purpose of the Group is to recognize key influencers in the Java community, provide advice, advance the adoption, and support the Java language and platform.
adoption of Java is "too broad". Is it the language? VM?

2024-06-03 12:33 UTC, mthmulders commented on site/documents/bylaws/bylaws.md
> +The purpose of the Group is to recognize key influencers in the Java community, provide advice, advance the adoption, and support the Java language and platform.
How about

```suggestion
The purpose of the Group is to recognize key influencers in the Java community, provide advice, support and advance the adoption of the Java language and platform.
```

The original text said, "The purpose of the Group is to [...], advance the adoption, and support the Java language and platform."; in those words, it's equally unclear to me what/whose adoption the group seeks to advance.

2024-06-03 17:48 UTC, hendrikebbers commented on site/documents/bylaws/bylaws.md
> +A member may renounce their membership at any time by submitting a pull request to update their status in the [Java Champions List](https://github.com/aalmiray/java-champions/blob/main/java-champions
I see zero overhead here and only benefits. What overhead would @aalmiray have if he would have the exactly same rights in a different repo?

2024-06-04 01:34 UTC, windust commented on site/documents/bylaws/bylaws.md
> +The purpose of the Group is to recognize key influencers in the Java community, provide advice, advance the adoption, and support the Java language and platform.
I like it! will update

2024-06-04 01:37 UTC, windust commented on site/documents/bylaws/bylaws.md
> +The Group use of the Java Champions Logo is subject to Oracle's Term and Conditions. In particular the Group cannot create any merchandise that bears the Java Champions Logo
Maybe to unblock we can just remove the last sentence that says "In particular the Group cannot create any merchandise that bears the Java Champions Logo"... We can then just discuss what is the extent of the usage terms

2024-06-04 01:46 UTC, windust commented on site/documents/bylaws/bylaws.md
> +Members have the right to attend meetings, vote on the Group matters, and participate in the Group activities. They are responsible for upholding the Group's mission and adhering to these bylaws.
I'll change it to "purpose". that refers to within the document and we can expand on that if we need to

2024-06-04 01:49 UTC, windust commented on site/documents/bylaws/bylaws.md
> +A member may renounce their membership at any time by submitting a pull request to update their status in the [Java Champions List](https://github.com/aalmiray/java-champions/blob/main/java-champions
True.. the PR is to lighten the load on maintaining the list... I do think that renouncing happens so rarely that it may not be an issue to keep it without the PR.  Will update.

2024-06-04 12:43 UTC, hendrikebbers commented on site/documents/bylaws/bylaws.md
> +The Group use of the Java Champions Logo is subject to Oracle's Term and Conditions. In particular the Group cannot create any merchandise that bears the Java Champions Logo
I would remove the full section for now. We can than discuss it on the mailing list

2024-06-05 15:49 UTC, kito99 commented on site/documents/bylaws/bylaws.md
> +A Group member nominates an individual by submitting the nomination form. The nomination form is created and maintained by the Group. The nomination requires both a nominator and a co-nominator.
Should we provide a link to the form?

2024-06-05 15:52 UTC, aalmiray commented on site/documents/bylaws/bylaws.md
> +A Group member nominates an individual by submitting the nomination form. The nomination form is created and maintained by the Group. The nomination requires both a nominator and a co-nominator.
No. The form is private for a reason and must remain as such. It has been exploited before.

2024-06-05 15:58 UTC, kito99 commented on site/documents/bylaws/bylaws.md
> +A member may renounce their membership at any time by submitting a pull request to update their status in the [Java Champions List](https://github.com/aalmiray/java-champions/blob/main/java-champions
+1 for org

2024-06-05 17:25 UTC, windust commented on site/documents/bylaws/bylaws.md
> +Voting on amendments to these bylaws shall be conducted by secret poll to ensure both transparency and privacy. Each member's vote shall be recorded without disclosing individual voting preferences.
Updated to be transparent (yeah! I think so )

2024-06-05 17:52 UTC, aalmiray commented on site/documents/bylaws/bylaws.md
> +The purpose of the Group is to recognize key influencers in the Java community, provide advice, advance the adoption, and support the Java language and platform.
"Java language and platform" implies other JVM languages get the boot

2024-06-05 19:22 UTC, windust commented on site/documents/bylaws/bylaws.md
> +The purpose of the Group is to recognize key influencers in the Java community, provide advice, advance the adoption, and support the Java language and platform.
This is an interesting conundrum... we are the Java Champions (but our name doesn't imply that we are giving the other languages the boot), so I do think is fair to align our name to the purpose... 

we could write it as 
"The purpose of the Group is to recognize key influencers in the Java community, offer advice, support, and promote the adoption of JVM-hosted languages and the platform"... but I believe maybe that's too broad. I do think specialization help us here (like we are not saying 'don't promote kotlin/scala', but the focus of the group is around Java and JVM. Like I think is a teeny weird if we do "State of the Scala Ecosystem" as part of a java champions publication.

2024-06-06 22:20 UTC, windust commented on site/documents/bylaws/bylaws.md
> +The purpose of the Group is to recognize key influencers in the Java community, provide advice, advance the adoption, and support the Java language and platform.
will update

2024-06-06 22:21 UTC, windust commented on site/documents/bylaws/bylaws.md
> +The Group use of the Java Champions Logo is subject to Oracle's Term and Conditions. In particular the Group cannot create any merchandise that bears the Java Champions Logo
removed... yeah, we can come back to it if it becomes necessary

2024-06-06 22:27 UTC, windust commented on site/documents/bylaws/bylaws.md
> +Members have the right to attend meetings, vote on the Group matters, and participate in the Group activities. They are responsible for upholding the Group's mission and adhering to these bylaws.
Resolving as being a JC doesn't give you responsibilities to the group.

2024-06-07 19:34 UTC, edeandrea commented on site/documents/bylaws/bylaws.md
> +Membership is open to individuals who have been nominated by a current Group member and approved by the Group and are not Oracle Employees.
Since the nomination section below states that a nomination requires both a nominator and a co-nominator, should this be reworded to say that membership is open to individuals who have been nominated by at least two current Group members?

2024-06-07 19:36 UTC, edeandrea commented on site/documents/bylaws/bylaws.md
> +A Group member nominates an individual by submitting the nomination form. The nomination form is created and maintained by the Group. The nomination requires both a nominator and a co-nominator.
Are there any rules around whether the nominator and/or co-nominator have to work for a different organization than the individual?

2024-06-07 19:38 UTC, edeandrea commented on site/documents/bylaws/bylaws.md
> +### Section 7: Results
Are there any rules about the nominator/co-nominator being able to vote or if they should abstain?

2024-06-07 19:42 UTC, edeandrea commented on site/documents/bylaws/bylaws.md
> +A member may renounce their membership at any time by submitting a pull request to update their status in the [Java Champions List](https://github.com/aalmiray/java-champions/blob/main/java-champions
+1 for an org

2024-06-09 09:56 UTC, struberg commented on site/documents/bylaws/bylaws.md
> + 2. Alumni: Members that have joined Oracle after becoming Java Champions
Does an Alumni member automatically get reinitiated as full member when he leaves Oracle again? In which case it would be more like a 'Suspended' status?

2024-06-09 10:56 UTC, struberg commented on site/documents/bylaws/bylaws.md
> +- Two negative ("-1") votes will disqualify a candidate.
I'm not quite sure if the rule with a fixed number of 2 -1 votes forming a binding VETO will scale well. What about requiring a 90% quorum of all casted non-abstain votes? 
That would mean that >=10% -1 of all casted +1 votes will result in a negative outcome.

Also note that usually if there is a -1 with a good reasoning, then others often will retract their former +1 vote as well.

2024-06-10 06:49 UTC, mthmulders commented on site/documents/bylaws/bylaws.md
> +A Group member nominates an individual by submitting the nomination form. The nomination form is created and maintained by the Group. The nomination requires both a nominator and a co-nominator.
I don't think there are, but I would be interested in having a public conversation on the ML about this.

2024-06-11 03:10 UTC, windust commented on site/documents/bylaws/bylaws.md
> +Membership is open to individuals who have been nominated by a current Group member and approved by the Group and are not Oracle Employees.
good suggestion! will update.

2024-06-11 03:13 UTC, windust commented on site/documents/bylaws/bylaws.md
> +A Group member nominates an individual by submitting the nomination form. The nomination form is created and maintained by the Group. The nomination requires both a nominator and a co-nominator.
Not explicitly, but implicitly it was usually seen as not a good nomination if it was sponsored by someone that worked in the same company
 
There was also another implicit (social) contract that folks that worked at the "same" company would not vote? But again, nothing as far as I know in the 'rules' but mostly what folks thought it would be fair (I think we rarely had to bring that up in the ML)

2024-06-11 03:14 UTC, windust commented on site/documents/bylaws/bylaws.md
> +### Section 7: Results
Don't think there were rules around this... but still most folks would behave as we thought they would (i.e. if they nominate they usually abstain)... we could make it explicit but maybe we do that as an update after this?

2024-06-11 03:15 UTC, windust commented on site/documents/bylaws/bylaws.md
> +- Two negative ("-1") votes will disqualify a candidate.
I think this could be a discussion and then maybe an amendment? (at least for now I'm trying to capture what we know is the current rules)

2024-06-15 16:13 UTC, kcpeppe commented on site/documents/bylaws/bylaws.md
> +Once a nomination has been submitted and processed by Oracle's Java Champion Team, it will be announced on the Java Champions Mailing List. This initiates a two-week discussion period during which Ja
It has always been the case that a member can ask for an extension in cases where more time is needed to gather more information.

2024-06-15 16:14 UTC, kcpeppe commented on site/documents/bylaws/bylaws.md
> +A vote of "-1" carries significant weight against the nomination. Java Champions voting "-1" must provide a reason for their disapproval.
Ideally, the reasoning for disapproval would have come out during the discussion period.

2024-06-15 16:18 UTC, kcpeppe commented on site/documents/bylaws/bylaws.md
> +A member may renounce their membership at any time by submitting a pull request to remove themselves from the [Java Champions List](https://github.com/aalmiray/java-champions/blob/main/java-champions
I would think that to renounce one would have to inform Oracle and have their name removed from it's list. Removing from this site would be a courtesy.

2024-06-15 16:35 UTC, kcpeppe commented on site/documents/bylaws/bylaws.md
> +Voting on amendments to these bylaws shall be conducted by secret poll to ensure both transparency and privacy. Each member's vote shall be recorded without disclosing individual voting preferences.
IMO, 1 week is too short for discussions of amendments and we should be afforded the flexablity to extend as needed.

As has been pointed out, this is different than the nomination process where we seek consensus Here we should seek either a 90% or 67% majority vote with possibly a minimum participation threshold (of say, 50%??).

2024-06-15 21:35 UTC, windust commented on site/documents/bylaws/bylaws.md
> +Voting on amendments to these bylaws shall be conducted by secret poll to ensure both transparency and privacy. Each member's vote shall be recorded without disclosing individual voting preferences.
maybe we can say a "minimum" of one week and leave it to the submitter to give a longer timeline. I do think there might be small updates that could be voted on in a week

2024-06-15 21:36 UTC, windust commented on site/documents/bylaws/bylaws.md
> +A member may renounce their membership at any time by submitting a pull request to remove themselves from the [Java Champions List](https://github.com/aalmiray/java-champions/blob/main/java-champions
(ah, that one is outdated, yeah, is more of a announcement on the list and then we take care of removing from the yml (this is such a small incidence that I feel is not a burden we need to worry too much about

2024-06-16 22:50 UTC, evanchooly commented on site/documents/bylaws/bylaws.md
> +Voting on amendments to these bylaws shall be conducted by secret poll to ensure both transparency and privacy. Each member's vote shall be recorded without disclosing individual voting preferences.
A month would not be unreasonable with minimum vote participation thresholds.

2024-06-17 07:46 UTC, jodastephen commented on site/documents/bylaws/bylaws.md
> +Voting is not compulsory, so Group members may choose not to participate in a candidate nomination.
How about adding something like "This is effectively equivalent to voting "0".

2024-06-17 07:47 UTC, jodastephen commented on site/documents/bylaws/bylaws.md
> +## Article III: Meetings
You need something to cover Oracle setting up and running a meeting/event

2024-06-17 14:39 UTC, JOpsDev commented on site/documents/bylaws/bylaws.md
> +The Group operates under the Java Champions Oracle Trademark; therefore, these bylaws must be considered in the context of the Trademark.
I could find the "Java" trademark, but not a "Java Champions Oracle" trademark. What is it?

2024-06-17 14:39 UTC, JOpsDev commented on site/documents/bylaws/bylaws.md
> +Once a nomination has been submitted and processed by Oracle's Java Champion Team, it will be announced on the Group Mailing List. This initiates a two-week discussion period during which Group membe
This period is a change from the current "concerns only" period, right?
What were the reasons to introduce such a "concerns only" phase in the beginning. Why should this be changed?

2024-06-19 18:06 UTC, windust commented on site/documents/bylaws/bylaws.md
> +Voting is not compulsory, so Group members may choose not to participate in a candidate nomination.
I think technically voting "0" may count to things like quorum (if we update these), so it would look like we always have quorum since everyone voted... I would rather start here where if you don't vote, it's not there.

2024-06-19 18:30 UTC, windust commented on site/documents/bylaws/bylaws.md
> + 2. Alumni: Members that have joined Oracle after becoming Java Champions
updated in the oracle employees section

2024-06-19 18:33 UTC, windust commented on site/documents/bylaws/bylaws.md
> +A member may renounce their membership at any time by submitting a pull request to remove themselves from the [Java Champions List](https://github.com/aalmiray/java-champions/blob/main/java-champions
updated to just notify their intent to their mailing list.

2024-06-24 18:15 UTC, bsbodden commented on site/documents/bylaws/bylaws.md
> +A member may renounce their membership at any time by submitting a pull request to update their status in the [Java Champions List](https://github.com/aalmiray/java-champions/blob/main/java-champions
+1 for an org

2024-06-24 22:54 UTC, rodrigolgraciano commented on site/documents/bylaws/bylaws.md
> +Voting is not compulsory, so Group members may choose not to participate in a candidate nomination.
As we are now 400 members, perhaps we should increase the numbers of +1 required for a nomination?

2024-06-26 05:51 UTC, JOpsDev commented on site/documents/bylaws/bylaws.md
> +Amendments must be approved by a two-thirds majority of the members voting in the poll.
7 days is way to short. Why such a rush? Someone might be on holidays for 14 or 21 days. Ok, it's not a blocker if we miss one vote. On the other hand these things should evolve slowly, so why not 4 weeks?

2024-06-26 07:11 UTC, michaelhuettermann commented on site/documents/bylaws/bylaws.md
> +### Section 7: Results
Yes, in fact one additional +1 would be sufficient. Why should a nominator vote?

2024-06-26 07:15 UTC, michaelhuettermann commented on site/documents/bylaws/bylaws.md
> +Voting is not compulsory, so Group members may choose not to participate in a candidate nomination.
A section on quorum is missing right now e.g. for amendments. Please add.

2024-06-26 18:37 UTC, aalmiray commented
Everyone, at the moment @windust "owns" the bylaws document as he started the document, that is, he's the only one with the responsibility and capacity to accept suggestions at this point. If you have any suggestions for changes use the review mechanism. IF and WHEN this document gets accepted and merged, THEN and only THEN @windust's sole ownership disappears. After that, any further changes will only be accepted via PRs following the agreed upon amendment process.

@kcpeppe your commit was reverted as it was a direct push to the document without any reviews. Please use the review button to submit your suggested changes.

2024-06-28 08:17 UTC, Emily-Jiang commented on site/documents/bylaws/bylaws.md
> +Following the discussion period, a minimum of one-week voting period is set aside for open polling through the mailing list. The proposing member should announce the length of the voting period.
It is better to use days as week might have different interpretation for week days whether to include weekend or not.

2024-07-01 20:29 UTC, merged